import { useState, useCallback } from "react";
import TripForm from "../components/TripForm";
import TripResults from "../components/TripResults";
import LoadingSkeleton from "../components/LoadingSkeleton";
import type { TripFormData } from "../components/TripForm";
import type { TripData } from "../components/TripResults";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";

// Mock AI generation (will be replaced with Gemini edge function)
const generateMockTrip = (form: TripFormData): TripData => {
  const budgetPriceMap: Record<string, string> = {
    budget: "$40–80/night",
    moderate: "$100–200/night",
    luxury: "$300–600/night",
  };

  return {
    tripName: `${form.destination} — ${form.days}-Day ${form.budget.charAt(0).toUpperCase() + form.budget.slice(1)} Trip`,
    destination: form.destination,
    days: form.days,
    budget: form.budget,
    partner: form.partner,
    hotels: [
      {
        name: `Grand ${form.destination.split(",")[0]} Hotel`,
        price: budgetPriceMap[form.budget] || "$100–200/night",
        rating: 4.5,
        description: `A well-rated hotel in the heart of ${form.destination} with excellent amenities and central location.`,
      },
      {
        name: `${form.destination.split(",")[0]} Boutique Stay`,
        price: budgetPriceMap[form.budget] || "$100–200/night",
        rating: 4.3,
        description: `Charming boutique accommodation with local character and modern comforts.`,
      },
      {
        name: `The ${form.destination.split(",")[0]} Residence`,
        price: budgetPriceMap[form.budget] || "$100–200/night",
        rating: 4.7,
        description: `Premium residence offering spacious rooms and top-tier service.`,
      },
    ],
    itinerary: Array.from({ length: form.days }, (_, i) => ({
      day: i + 1,
      theme: i === 0 ? "Arrival & Orientation" : i === form.days - 1 ? "Departure Day" : `Exploration Day ${i + 1}`,
      activities: [
        {
          time: "09:00",
          task: i === 0 ? "Check-in & settle" : "Morning activity",
          description: i === 0
            ? `Arrive at your hotel in ${form.destination}. Freshen up and get oriented with the neighborhood.`
            : `Start the day exploring local highlights of ${form.destination}.`,
        },
        {
          time: "12:30",
          task: "Lunch",
          description: `Enjoy a ${form.budget === "luxury" ? "fine dining" : "local"} lunch experience.`,
        },
        {
          time: "14:00",
          task: i === form.days - 1 ? "Pack & checkout" : "Afternoon exploration",
          description: i === form.days - 1
            ? "Pack your bags and check out. Head to the airport or station."
            : `Visit key attractions and immerse in the local culture of ${form.destination}.`,
        },
        {
          time: "19:00",
          task: "Evening",
          description: i === form.days - 1
            ? "Safe travels home!"
            : `Dinner and evening stroll through ${form.destination.split(",")[0]}.`,
        },
      ],
    })),
  };
};

const Index = () => {
  const { user } = useAuth();
  const [isLoading, setIsLoading] = useState(false);
  const [tripResult, setTripResult] = useState<TripData | null>(null);
  const [isSaved, setIsSaved] = useState(false);

  const handleSubmit = useCallback(async (data: TripFormData) => {
    setIsLoading(true);
    setTripResult(null);
    setIsSaved(false);

    try {
      // Try AI generation via edge function
      const { data: aiData, error } = await supabase.functions.invoke("generate-trip", {
        body: data,
      });

      if (error || !aiData || aiData.error) {
        // Fallback to mock data
        console.warn("AI generation unavailable, using mock data:", error || aiData?.error);
        const trip = generateMockTrip(data);
        setTripResult(trip);
        toast.success("Itinerary generated (demo mode).");
      } else {
        setTripResult({
          tripName: aiData.tripName,
          destination: data.destination,
          days: data.days,
          budget: data.budget,
          partner: data.partner,
          hotels: aiData.hotels,
          itinerary: aiData.itinerary,
        });
        toast.success("Itinerary generated by AI. You're ready to go.");
      }
    } catch {
      const trip = generateMockTrip(data);
      setTripResult(trip);
      toast.success("Itinerary generated (demo mode).");
    } finally {
      setIsLoading(false);
    }
  }, []);

  const handleSave = useCallback(async () => {
    if (!tripResult || !user) return;

    try {
      const { error } = await supabase.from("trips").insert({
        user_id: user.id,
        trip_name: tripResult.tripName,
        destination: tripResult.destination,
        days: tripResult.days,
        budget: tripResult.budget,
        partner: tripResult.partner,
        hotels: tripResult.hotels as any,
        itinerary: tripResult.itinerary as any,
      });
      if (error) throw error;
      setIsSaved(true);
      toast.success("Trip saved to My Trips.");
    } catch {
      toast.error("Failed to save trip.");
    }
  }, [tripResult, user]);

  const handleBack = useCallback(() => {
    setTripResult(null);
    setIsSaved(false);
  }, []);

  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 py-8 sm:py-12">
      {isLoading ? (
        <LoadingSkeleton />
      ) : tripResult ? (
        <TripResults trip={tripResult} onBack={handleBack} onSave={handleSave} isSaved={isSaved} />
      ) : (
        <TripForm onSubmit={handleSubmit} isLoading={isLoading} />
      )}
    </div>
  );
};

export default Index;
